insert into Categoria (Nombre_categoria) values ('Desayunos');
insert into Categoria (Nombre_categoria) values ('Tacos');
insert into Categoria (Nombre_categoria) values ('Bebidas');
insert into Categoria (Nombre_categoria) values ('Cervezas');
insert into Categoria (Nombre_categoria) values ('Pulques');
insert into Categoria (Nombre_categoria) values ('Snacks');
insert into Categoria (Nombre_categoria) values ('Caldos');
insert into Categoria (Nombre_categoria) values ('Tostadas');
insert into Categoria (Nombre_categoria) values ('Quesadillas');
insert into Categoria (Nombre_categoria) values ('Bebidas calientes');
insert into Categoria (Nombre_categoria) values ('Bebidas frias');
insert into Categoria (Nombre_categoria) values ('Postres');
insert into Categoria (Nombre_categoria) values ('Sopes');
insert into Categoria (Nombre_categoria) values ('Huaraches');
