insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(1,'cervezas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(1,'cervezas','amargo','dia festivo','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(2,'cervezas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(2,'cervezas','amargo','dia festivo','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(3,'cervezas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(3,'cervezas','amargo','dia festivo','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(4,'cervezas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(4,'cervezas','amargo','dia festivo','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(5,'cervezas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(5,'cervezas','amargo','dia festivo','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(6,'pulques','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(6,'pulques','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(7,'bebidas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(7,'bebidas','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(7,'bebidas','acido','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(7,'bebidas','amargo','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(8,'bebidas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(8,'bebidas','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(8,'bebidas','acido','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(8,'bebidas','amargo','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(9,'bebidas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(9,'bebidas','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(9,'bebidas','acido','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(9,'bebidas','amargo','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(10,'bebidas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(10,'bebidas','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(10,'bebidas','acido','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(10,'bebidas','amargo','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(11,'bebidas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(11,'bebidas','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(11,'bebidas','acido','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(11,'bebidas','amargo','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(12,'pulques','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(12,'pulques','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(13,'pulques','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(13,'pulques','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(14,'pulques','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(14,'pulques','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(15,'cervezas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(15,'cervezas','amargo','dia festivo','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(15,'cervezas','amargo','verano','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(16,'cervezas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(16,'cervezas','amargo','dia festivo','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(16,'cervezas','amargo','verano','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(17,'cervezas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(17,'cervezas','amargo','dia festivo','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(17,'cervezas','amargo','verano','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(18,'cervezas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(18,'cervezas','amargo','dia festivo','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(18,'cervezas','amargo','verano','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(19,'cervezas','amargo','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(19,'cervezas','amargo','dia festivo','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(19,'cervezas','amargo','verano','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(20,'pulques','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(20,'pulques','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(21,'pulques','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(21,'pulques','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(22,'pulques','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(22,'pulques','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(23,'pulques','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(23,'pulques','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(24,'pulques','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(24,'pulques','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(25,'pulques','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(25,'pulques','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(26,'pulques','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(26,'pulques','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(27,'pulques','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(27,'pulques','acido','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(28,'bebidas','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(28,'bebidas','dulce','verano','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(28,'bebidas','dulce','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(29,'bebidas','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(29,'bebidas','dulce','verano','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(29,'bebidas','dulce','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(30,'bebidas','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(30,'bebidas','dulce','verano','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(30,'bebidas','dulce','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(31,'bebidas','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(31,'bebidas','dulce','verano','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(31,'bebidas','dulce','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(32,'bebidas','dulce','tarde','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(32,'bebidas','dulce','verano','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(32,'bebidas','dulce','noche','frio');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(33,'bebidas','dulce','noche','temblado');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(33,'bebidas','acido','noche','templado');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(33,'bebidas','dulce','cena','templado');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(33,'bebidas','acido','cena','templado');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(33,'bebidas','dulce','dia festivo','templado');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(33,'bebidas','acido','dia festivo','templado');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(34,'caldos','picante','comida','caliente');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(34,'caldos','picante','dia festivo','caliente');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(34,'caldos','picante','otoño','caliente');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(35,'caldos','picante','comida','caliente');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(35,'caldos','picante','dia festivo','caliente');
insert into Contenido_Platillo(id_Platillo, Tipo, Sabor, Ocacion, Temperatura) values(35,'caldos','picante','otoño','caliente');
