insert into Ingrediente (Nombre_ingrediente) values ('Carne para hamburgesa');
insert into Ingrediente (Nombre_ingrediente) values ('Sal');
insert into Ingrediente (Nombre_ingrediente) values ('Tajin');
insert into Ingrediente (Nombre_ingrediente) values ('Limon');
insert into Ingrediente (Nombre_ingrediente) values ('clamato');
insert into Ingrediente (Nombre_ingrediente) values ('pimienta');
insert into Ingrediente (Nombre_ingrediente) values ('salsa maggi');
insert into Ingrediente (Nombre_ingrediente) values ('chamoy');
insert into Ingrediente (Nombre_ingrediente) values ('jugo de naranja');
insert into Ingrediente (Nombre_ingrediente) values ('miguelito');
insert into Ingrediente (Nombre_ingrediente) values ('banderilla de tamarindo');
insert into Ingrediente (Nombre_ingrediente) values ('Totilla de maiz');
insert into Ingrediente (Nombre_ingrediente) values ('Totopos de maiz');
insert into Ingrediente (Nombre_ingrediente) values ('Grano de maiz');
insert into Ingrediente (Nombre_ingrediente) values ('Chiles rojos secos');
insert into Ingrediente (Nombre_ingrediente) values ('Carne de cerdo');
insert into Ingrediente (Nombre_ingrediente) values ('Carne de pollo');
insert into Ingrediente (Nombre_ingrediente) values ('Ajo');
insert into Ingrediente (Nombre_ingrediente) values ('Cebolla');
insert into Ingrediente (Nombre_ingrediente) values ('Chiles verdes');
insert into Ingrediente (Nombre_ingrediente) values ('Chiles rojos');
insert into Ingrediente (Nombre_ingrediente) values ('Crema');
insert into Ingrediente (Nombre_ingrediente) values ('Queso rallado');
insert into Ingrediente (Nombre_ingrediente) values ('Queso oaxaca');
insert into Ingrediente (Nombre_ingrediente) values ('Tostada de maiz');
insert into Ingrediente (Nombre_ingrediente) values ('Carne de res');
insert into Ingrediente (Nombre_ingrediente) values ('pata de res');
insert into Ingrediente (Nombre_ingrediente) values ('Carne de cabra');
insert into Ingrediente (Nombre_ingrediente) values ('Suadero');
insert into Ingrediente (Nombre_ingrediente) values ('Bistec de res');
insert into Ingrediente (Nombre_ingrediente) values ('Frijoles');
insert into Ingrediente (Nombre_ingrediente) values ('Longaniza');
insert into Ingrediente (Nombre_ingrediente) values ('Rebanada de pan');
insert into Ingrediente (Nombre_ingrediente) values ('tumaca');
insert into Ingrediente (Nombre_ingrediente) values ('queso provolone');
insert into Ingrediente (Nombre_ingrediente) values ('Alioli');
insert into Ingrediente (Nombre_ingrediente) values ('Jitomate');
insert into Ingrediente (Nombre_ingrediente) values ('Salsa verde');
insert into Ingrediente (Nombre_ingrediente) values ('Salsa roja');
insert into Ingrediente (Nombre_ingrediente) values ('Lechuga');
insert into Ingrediente (Nombre_ingrediente) values ('Milanesa de pollo');
insert into Ingrediente (Nombre_ingrediente) values ('Pollo con chipotle');
insert into Ingrediente (Nombre_ingrediente) values ('Papas con chorizo');
insert into Ingrediente (Nombre_ingrediente) values ('Champiñones');
insert into Ingrediente (Nombre_ingrediente) values ('Piña');
insert into Ingrediente (Nombre_ingrediente) values ('Fresa');
insert into Ingrediente (Nombre_ingrediente) values ('Menta');
insert into Ingrediente (Nombre_ingrediente) values ('Horchata');
insert into Ingrediente (Nombre_ingrediente) values ('Mango');
insert into Ingrediente (Nombre_ingrediente) values ('Salchicha');
insert into Ingrediente (Nombre_ingrediente) values ('Alitas de pollo');
insert into Ingrediente (Nombre_ingrediente) values ('papa');
insert into Ingrediente (Nombre_ingrediente) values ('Tortilla de harina');
insert into Ingrediente (Nombre_ingrediente) values ('Jamon');
insert into Ingrediente (Nombre_ingrediente) values ('Salsa Catsup');
insert into Ingrediente (Nombre_ingrediente) values ('Queso amarillo');
insert into Ingrediente (Nombre_ingrediente) values ('Mostaza');
insert into Ingrediente (Nombre_ingrediente) values ('Cafe molido');
insert into Ingrediente (Nombre_ingrediente) values ('Leche entera');
insert into Ingrediente (Nombre_ingrediente) values ('Leche deslactosada');
insert into Ingrediente (Nombre_ingrediente) values ('Cajeta');
insert into Ingrediente (Nombre_ingrediente) values ('Manzanilla');
insert into Ingrediente (Nombre_ingrediente) values ('Hierbabuena');
insert into Ingrediente (Nombre_ingrediente) values ('Hierbas relajantes');
insert into Ingrediente (Nombre_ingrediente) values ('Canela');
insert into Ingrediente (Nombre_ingrediente) values ('Manzana');
insert into Ingrediente (Nombre_ingrediente) values ('Saborizante de galleta Oreo');
insert into Ingrediente (Nombre_ingrediente) values ('Saborizante de capuchino');
insert into Ingrediente (Nombre_ingrediente) values ('Saboriante de cajeta');
insert into Ingrediente (Nombre_ingrediente) values ('Saborizante de moka');
insert into Ingrediente (Nombre_ingrediente) values ('Saborizante de mango');
insert into Ingrediente (Nombre_ingrediente) values ('Saborizante de fresa');
insert into Ingrediente (Nombre_ingrediente) values ('Saborizante de tamarindo');
insert into Ingrediente (Nombre_ingrediente) values ('Helado de fresa');
insert into Ingrediente (Nombre_ingrediente) values ('Helado de vainilla');
insert into Ingrediente (Nombre_ingrediente) values ('Helado de chocolate');
insert into Ingrediente (Nombre_ingrediente) values ('Mermelada de fresa');
insert into Ingrediente (Nombre_ingrediente) values ('Chocolate');
insert into Ingrediente (Nombre_ingrediente) values ('Polvo de chocolate');
insert into Ingrediente (Nombre_ingrediente) values ('Harina para hornear');
insert into Ingrediente (Nombre_ingrediente) values ('Levadura');
insert into Ingrediente (Nombre_ingrediente) values ('Lechera');
insert into Ingrediente (Nombre_ingrediente) values ('Azucar');
insert into Ingrediente (Nombre_ingrediente) values ('Platano');
insert into Ingrediente (Nombre_ingrediente) values ('Mazapan');
insert into Ingrediente (Nombre_ingrediente) values ('Cacahuate');
insert into Ingrediente (Nombre_ingrediente) values ('Piña colada');
insert into Ingrediente (Nombre_ingrediente) values ('Guayaba');
