insert into Platillo (Nombre_platillo, id_Categoria) values ('Cerveza Indio', 4);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cerveza Carta Blanca', 4);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cerveza Victoria', 4);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cerveza Tecate', 4);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cerveza Tecate Light', 4);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Pulque natural', 5);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Pulmon de Pina', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('La cura Fresa', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('El que nadie busca', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('El cura canibal', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('El tinto', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Curado de coco', 5);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cura de Tamarindo', 5);
insert into Platillo (Nombre_platillo, id_Categoria) values ('El guayabon', 5);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tarro Cubano', 4);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tarro chamo chela', 4);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tarro Michelada', 4);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tarro Chelado', 4);
insert into Platillo (Nombre_platillo, id_Categoria) values ('El del abuelo', 4);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Pulmon de Platano Mapazan', 5);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Pulmon de cacahuate y nuez', 5);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Pulmon de Toxica', 5);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Pulmon Rielero', 5);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Pulmon Rielero', 5);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Pulmon Pina Colada', 5);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Pulmon de mango colado', 5);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Pulmon de Guayaba colada', 5);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Viña Clericot', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Viña Sangria', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Viña Tinto de verano', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Viña Vino Caliente', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Viña Calimoxa', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Copa de vino tinto', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Birria', 7);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Pozole', 7);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Chilaquiles Verdes', 1);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Chilaquiles Rojos', 1);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Enchiladas Verdes', 1);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Enquiladas Suizas Verdes', 1);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Enchiladas Suizas Rojas', 1);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tostadas de tinga de res', 8);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tostadas de tinga de pollo', 8);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tostadas de Pata', 8);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tostadas de Bistec de res', 8);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Taco de Birria', 2);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Taco de Suadero', 2);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Taco Rielero', 2);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Taco de Bistec de res', 2);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Taco de Bistec de puerco', 2);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Taco de longaniza', 2);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Taco de Campechano', 2);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tapa Mexicana', 1);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tapa Jamon Serrano', 1);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tapa Lomo', 1);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tapa Salamanca', 1);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Quesadilla de bistec de res', 9);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tacos Dorados', 1);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Sopes de bistec de res', 13);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Huarache sencillo', 14);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Huaraches de bistec de res', 14);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tostadas de Bistec de puerco', 8);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tostadas de Milanesa de pollo', 8);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tostadas de Suadero', 8);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tostadas de Papa con Chorizo', 8);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tostadas de Carne de res en Birria', 8);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tostadas de Queso', 8);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tostadas de Longaniza', 8);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Tostadas de Champiñones', 8);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Quesadillas de bistec de puerco', 9);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Quedasillas de milanesa de pollo', 9);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Quesadillas de Tinga de Pollo', 9);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Quesadillas de Tinga de Res', 9);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Quesadillas de Suadero', 9);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Quesadillas de Papa con chorizo', 9);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Quesadillas de Carne de res en birria', 9);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Quesadillas de Queso', 9);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Quesadillas de Longaniza', 9);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Quesadillas de Champiñones', 9);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Huaraches de Bistec de Puerco', 14);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Huaraches de Milanesa de Pollo', 14);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Huaraches de Tinga de pollo', 14);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Huaraches de Tinga de res', 14);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Huaraches de Suadero', 14);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Huaraches de Papa con longaniza', 14);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Huaraches de carne de res de birria', 14);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Huarache de Queso', 14);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Huaraches de Longaniza', 14);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Huaraches de Champiñones', 14);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Sopes de bistec de puerco', 13);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Sopes de milanesa de pollo', 13);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Sopes de tinga de pollo', 13);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Sopes de tinga de res', 13);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Sopes de Suadero', 13);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Sopes de Papa con chorizo', 13);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Sopes de carne de res en Birria', 13);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Sopes de queso', 13);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Sopes de Longaniza', 13);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Sopes de Champiñones', 13);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Piñada Rielera', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Fresa Maniaka', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('La mentada', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Horchata Veracruzana', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('La mentirosa', 3);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Chamoyada de Mango', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('La Toxica', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cenizas la Rielera', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cantario revolucion', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Hot Dog', 6);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Alitas', 6);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Papas a la Francesa', 6);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Sincronizadas', 6);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Salchipulpos', 6);
insert into Platillo (Nombre_platillo, id_Categoria) values ('hamburgesa', 6);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cafe expresso', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cafe expresso doble', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cafe expresso cortado', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cafe Americano', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cafe Americano cortado', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Capuchino', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Capuchino de cajeta', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Lechero estilo Veracruz', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Te verde', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Te Hierbabuena', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Te Manzanilla', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Te Manzana Canela', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Te Hierbas Relajantes', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Te Limon', 10);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Frappe Oreo', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Frappe Capuchino', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Frappe Cajeta', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Frappe Moka', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Chamoyada de Fresa', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Chamoyada de Tamarindo', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Helado Rielero', 12);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Helado de fresa', 12);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Helado de Chocolate', 12);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Helado de vainilla', 12);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Cubilete Artesanal', 12);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Rebanada del Riel', 12);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Pastel Imposible', 12);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Malteada de fresa', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Malteada de Mango', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Malteada de Cajeta', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Malteada de Vainilla', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Malteada de Chocolate', 11);
insert into Platillo (Nombre_platillo, id_Categoria) values ('Licuados', 11);
